# Generated by Django 6.0.2 on 2026-02-17 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DeptNo', models.IntegerField(primary_key=True, serialize=False)),
                ('Dname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DocID', models.IntegerField(primary_key=True, serialize=False)),
                ('Dname', models.CharField(max_length=50)),
                ('Specialization', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('HelperID', models.IntegerField(primary_key=True, serialize=False)),
                ('Hname', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Helper',
            },
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('RecID', models.IntegerField(primary_key=True, serialize=False)),
                ('Rname', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Receptionist',
            },
        ),
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=128)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=100)),
                ('AdminType', models.ForeignKey(db_column='Admin', on_delete=django.db.models.deletion.CASCADE, to='HclsWebApi.admin')),
            ],
            options={
                'db_table': 'AdminLogin',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpID', models.IntegerField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=128)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Salary', models.FloatField()),
                ('Address', models.CharField(max_length=100)),
                ('IsActive', models.BooleanField(default=True)),
                ('IsAdmin', models.BooleanField(default=False)),
                ('IsLoggedIn', models.BooleanField(default=False)),
                ('DeptNo', models.ForeignKey(db_column='DeptNo', on_delete=django.db.models.deletion.CASCADE, to='HclsWebApi.department')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientID', models.IntegerField(primary_key=True, serialize=False)),
                ('Pname', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Prescription', models.CharField(max_length=250)),
                ('EntryDateandTime', models.DateTimeField(auto_now_add=True)),
                ('ExitDateandTime', models.DateTimeField(blank=True, null=True)),
                ('IsAdmitted', models.BooleanField(default=False)),
                ('Medication', models.CharField(max_length=250)),
                ('Bill', models.FloatField()),
                ('DoctorID', models.ForeignKey(db_column='DoctorID', on_delete=django.db.models.deletion.CASCADE, to='HclsWebApi.doctor')),
                ('HelperID', models.ForeignKey(db_column='HelperID', on_delete=django.db.models.deletion.CASCADE, related_name='helper_patients', to='HclsWebApi.employee')),
                ('ReceptionistID', models.ForeignKey(db_column='ReceptionistID', on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_patients', to='HclsWebApi.employee')),
            ],
        ),
    ]
