# Generated by Django 6.0.2 on 2026-02-18 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HclsWebApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='AdminType',
        ),
        migrations.AlterModelTable(
            name='admintype',
            table='AdminType',
        ),
    ]
