# Generated by Django 6.0.2 on 2026-02-18 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HclsWebApi', '0002_rename_admin_admintype_alter_admintype_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table='Patient',
        ),
    ]
