# Generated by Django 6.0.2 on 2026-02-18 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HclsWebApi', '0003_alter_patient_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlogin',
            name='AdminType',
            field=models.ForeignKey(db_column='AdminType', on_delete=django.db.models.deletion.CASCADE, to='HclsWebApi.admintype'),
        ),
    ]
